platform :ios, '9.0'

target 'BKWeiBo' do

  	pod 'AFNetworking', '~> 3.2.1'
  	pod 'SDWebImage', '~> 4.3.3'
	pod 'MJExtension', '~> 3.0.13'
	pod 'MJRefresh', '~> 3.1.15.3'
	pod 'SnapKit', '~> 4.0.0'
end
